_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
dataset:
    value: synthetic_academic_260
embedding_model:
    value: DistilBERT
